# Site settings
title: ScoutsEncoder
description: encode plain text into scouts' ciphers.

# Author Info
linkedin_username: YoussefRaafatNasry
email: YoussefRaafatNasry@gmail.com
github_username: YoussefRaafatNasry

# Build settings
markdown: kramdown
