# Site settings
title: ScoutsEncoder
description: encode plain text into scouts' ciphers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

email: YoussefRaafatNasry@gmail.com
github_username: YoussefRaafatNasry

# Build settings
markdown: kramdown
